<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.projectunified</groupId>
        <artifactId>block-util-spigot</artifactId>
        <version>5.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>block-util-spigot-vanilla</artifactId>
    <name>BlockUtil Spigot - Vanilla</name>

    <properties>
        <mc.version>1.13.2-R0.1-20191113.201242-53</mc.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.projectunified</groupId>
            <artifactId>block-util-spigot-simple</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>