<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.projectunified</groupId>
        <artifactId>block-util-spigot</artifactId>
        <version>5.0.0</version>
    </parent>

    <artifactId>block-util-spigot-test</artifactId>
    <name>BlockUtil Spigot - Test</name>

    <properties>
        <minelib.version>1.3.0</minelib.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <relocations>
                                <relocation>
                                    <pattern>io.github.projectunified.minelib</pattern>
                                    <shadedPattern>io.github.projectunified.blockutil.test.minelib</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.lewdev.probabilitylib</pattern>
                                    <shadedPattern>io.github.projectunified.blockutil.test.probabilitylib
                                    </shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <dependencies>
        <dependency>
            <groupId>io.github.projectunified</groupId>
            <artifactId>block-util-spigot-fawe</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.projectunified</groupId>
            <artifactId>block-util-spigot-folia</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.projectunified</groupId>
            <artifactId>minelib-plugin-base</artifactId>
            <version>${minelib.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.projectunified</groupId>
            <artifactId>minelib-plugin-command</artifactId>
            <version>${minelib.version}</version>
        </dependency>
    </dependencies>
</project>