<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.projectunified</groupId>
        <artifactId>block-util-spigot</artifactId>
        <version>5.0.0</version>
    </parent>

    <artifactId>block-util-spigot-we</artifactId>
    <name>BlockUtil Spigot - WorldEdit</name>

    <properties>
        <mc.version>1.13.2-R0.1-20191113.201242-53</mc.version>
    </properties>

    <repositories>
        <repository>
            <id>enginehub-repo</id>
            <url>https://maven.enginehub.org/repo/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.github.projectunified</groupId>
            <artifactId>block-util-spigot-simple</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!--suppress VulnerableLibrariesLocal -->
        <dependency>
            <groupId>com.sk89q.worldedit</groupId>
            <artifactId>worldedit-bukkit</artifactId>
            <version>7.2.13</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>